[package]
name = "advent_of_code_01"
version = "0.1.0"
authors = ["Florian Tieben <ftiebe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "advent_of_code_01"
path = "main.rs"
